### ISSUE TITLE
Funny but doesn't work :(

### ISSUE THREAD

**Issue by yaakov-h** [rainersigwald/NostalgiaLogger#1]
I built this repo with `dotnet build` and tried using it myself, but I'm getting fun runtime errors.

With the net472 version:

```
C:\Temp\sample-console-app>msbuild -l:C:\Temp\NostalgiaLogger\NostalgiaLogger\bin\Debug\net472\NostalgiaLogger.dll
MSBuild version 17.9.5+33de0b227 for .NET Framework
Build started 16-May-2024 3:43:16 PM.


Unhandled Exception: System.MissingMethodException: Constructor on type 'System.IO.MemoryStream' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.ReadValue(DeserializingResourceReader reader, Int32 dataPos, Boolean isString, ResourceLocator& locator)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetStream(String name, CultureInfo culture)
   at NostalgiaLogger.NostalgiaLogger.StartPlayback() in C:\Temp\NostalgiaLogger\NostalgiaLogger\NostalgiaLogger.cs:line 41
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

With the net6.0 version:

```
C:\Temp\sample-console-app>dotnet build -l:C:\Temp\NostalgiaLogger\NostalgiaLogger\bin\Debug\net6.0\NostalgiaLogger.dll
MSBuild version 17.9.4+90725d08d for .NET
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'NAudio, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'. The system cannot find the file specified.
File name: 'NAudio, Version=2.2.1.0, Culture=neutral, PublicKeyToken=e279aa5131008a41'
   at NostalgiaLogger.NostalgiaLogger.StartPlayback()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

The folder `sample-console-app` is the output of `dotnet new console -n sample-console-app`.

**Comment by rainersigwald** [comment]
@yaakov-h Wait you mean I should have actually tried it on `dotnet build`? 🙃

Works (on my machine™️) now, please let me know if it doesn't for you.

**Comment by yaakov-h** [comment]
It works for me on both `dotnet` and `msbuild`, thanks!
